server:
  port: 8083


spring:
  application:
    name: config-server

  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atul-patel-silver/Fin_Tracker_Config.git
          default-label: main
          timeout: 5
          clone-on-start: true  # try cloning of ht GitHub repo
          force-pull: true
#          username: atulpatel2001
#          password: 12345678

encrypt:
  key: 45D81EC1EF61DF9AD8D3E5BB397F9

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: none

    info:
      env:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


endpoints:
  shutdown:
    enabled: true


logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"